name = "nepal-election-2082-api"
main = "worker.js"
compatibility_date = "2024-09-25"

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "ELECTION_CACHE"
id = "382bd168233040b0bafaa7fbc848d072"
